### ISSUE TITLE
最新版本编译不过去

### ISSUE THREAD

**Issue by zmoon111** [huaban/elasticsearch-analysis-jieba#10]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:13 min
[INFO] Finished at: 2015-06-16T17:47:24+08:00
[INFO] Final Memory: 11M/151M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project elasticsearch-analysis-jieba: Could not resolve dependencies for project org.elasticsearch:elasticsearch-analysis-jieba:jar:0.0.4: Could not find artifact com.huaban:jieba-analysis:jar:1.0.2 in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by piaolingxue** [comment]
please try again @zmoon111

**Comment by piaolingxue** [comment]
It has been synchronized to the central repository, then it should be no problem.
