### ISSUE TITLE
ElasticSearch 1.5.0 更新了，jieba还更新吗

### ISSUE THREAD

**Issue by fshare** [huaban/elasticsearch-analysis-jieba#7]
ElasticSearch 1.5.0 更新了，jieba还更新吗

**Comment by piaolingxue** [comment]
目前最新版本支持 1.3.0

**Comment by tokikanno** [comment]
@fshare : 之前發了一個 PR ，讓這個 plugin 可以在 1.5 上用 (在 1.5.2 上測試的)，剛剛被 merge 進去，你可以再抓下來試試看。
